# Generated by Django 3.2 on 2022-03-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
