# Generated by Django 3.2 on 2022-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0007_auto_20220306_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Article', max_length=255),
        ),
    ]
