# Generated by Django 3.2 on 2022-03-14 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0009_auto_20220314_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blurb',
            field=models.CharField(default='Click title to see full post', max_length=255),
        ),
    ]
