# Generated by Django 3.2 on 2022-03-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsite', '0013_auto_20220314_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
